import Link from "next/link"
import './globals.css'
import Header from "@/components/header/header";
import Animation from "@/components/animation";
import Footer from "@/components/footer/footer";
import Providers from "@/providers";

export const metadata = {
  title: "Chop's portfolio",
  description: 'Generated by chop',
}

export default async function RootLayout({ children }) {
    const resp = await fetch('http://localhost:9999/topics');
    const topics = await resp.json();
  return (
    <html>
      <body>
        <Providers>
          {/* <Header/> */}
          <main className="bg-white dark: bg-black">
            {children}
          </main>
            <Animation/>
          <Footer/>
        </Providers>
      </body>
    </html>
  )
}
